### ISSUE TITLE
Infrastructure improvements

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBItest#129]
- [x] Replace on.exit() #121
- [x] Double-check with_invalid_connection() and with_closed_connection() tests #117
- [x] Completeness test #114
- [x] Make sure that no spec names are duplicated
- [x] Report all leaked warnings as errors #113
- [x] ~~Call gc() after each test #112~~
- [x] Warn about skip patterns that don't match any of the tests #84
- [x] stress_load_unload tests delete driver package #56
- [x] Reenable stress tests on Travis #39
- [x] Use "description" package #40
- [x] Test all returned data frames for consistency #126
- [x] Easy way to run a single test #136

**Comment by krlmlr** [comment]
Closed in  13dc482.
